# Generated by Django 3.0 on 2020-02-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191223_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=25, unique=True, verbose_name='email address'),
        ),
    ]
