# Generated by Django 3.0 on 2020-02-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_friendship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='creator',
            new_name='user_one',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='friend',
            new_name='user_two',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='blocked',
        ),
        migrations.AddField(
            model_name='friendship',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
