# Generated by Django 3.0 on 2020-02-13 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200212_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='action_user_id',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='user_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='user_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_two', to=settings.AUTH_USER_MODEL),
        ),
    ]
