# Generated by Django 3.0 on 2020-02-13 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200212_2134'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('user_one', 'user_two')},
        ),
    ]
