# Generated by Django 3.0 on 2020-02-18 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200212_2138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
