# Generated by Django 3.0 on 2020-03-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200221_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_image',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
