# Generated by Django 3.0 on 2020-03-08 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_customuser_user_image'),
        ('users', '0008_friendship'),
    ]

    operations = [
    ]
