# Generated by Django 3.0 on 2020-03-08 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_merge_20200307_2304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
