# Generated by Django 3.0 on 2020-05-17 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_auto_20200517_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='status',
        ),
    ]
