# Generated by Django 3.0 on 2020-04-06 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('party', '0002_auto_20200404_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='song',
            name='likes',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='rating',
            field=models.ManyToManyField(to='party.Rating'),
        ),
    ]
