# Generated by Django 3.0.5 on 2020-06-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_auto_20200607_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
