# Generated by Django 3.0 on 2020-04-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_auto_20200405_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='cover_uri',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
