# Generated by Django 3.0 on 2020-04-13 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0004_auto_20200406_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='cover_uri',
        ),
        migrations.AddField(
            model_name='party',
            name='currently_playing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currently_playing', to='party.Song'),
        ),
    ]
