# Generated by Django 3.0 on 2020-04-13 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('party', '0005_auto_20200412_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='song',
            name='requester',
        ),
        migrations.CreateModel(
            name='SuggestedSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.ManyToManyField(to='party.Rating')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song', to='party.Song')),
            ],
        ),
        migrations.AlterField(
            model_name='party',
            name='queue',
            field=models.ManyToManyField(to='party.SuggestedSong'),
        ),
    ]
