# Generated by Django 3.0 on 2020-06-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(default=0)),
                ('action_user_id', models.SmallIntegerField(default=0)),
                ('permissions', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
